"""empty message

Revision ID: eedbb5c9e4e4
Revises: 
Create Date: 2026-01-19 17:17:55.669252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eedbb5c9e4e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno_disciplina', schema=None) as batch_op:
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('aluno_grupo_estudo', schema=None) as batch_op:
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('grupo_estudo_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('aluno_sessao_tutoria', schema=None) as batch_op:
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('sessao_tutoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('professor_disciplina', schema=None) as batch_op:
        batch_op.alter_column('professor_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('professor_orientador_disciplina', schema=None) as batch_op:
        batch_op.alter_column('professor_orientador_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professor_orientador_disciplina', schema=None) as batch_op:
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('professor_orientador_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('professor_disciplina', schema=None) as batch_op:
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('professor_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('aluno_sessao_tutoria', schema=None) as batch_op:
        batch_op.alter_column('sessao_tutoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('aluno_grupo_estudo', schema=None) as batch_op:
        batch_op.alter_column('grupo_estudo_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('aluno_disciplina', schema=None) as batch_op:
        batch_op.alter_column('disciplina_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('aluno_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
